---
- name: Copy over Jenkins Worker Node creation payload xml
  vars: 
    ipv4: "{{ ansible_default_ipv4.address }}"
  template:
    src: templates/node.xml.j2
    dest: /home/ec2-user/node.xml
    owner: ec2-user
    mode: '0644'

- name: Read generated private key id_rsa
  slurp:
    src: /home/ec2-user/.ssh/id_rsa
  register: pkey

- name: Copy over creds.xml and create Jenkins credential
  vars:
    priv_key: "{{ pkey['content'] | b64decode }}"
    ipv4: "{{ ansible_default_ipv4.address }}"
  template:
    src: templates/cred-privkey.j2
    dest: /home/ec2-user/creds.xml
