---
- name: Get Jenkins CLI jar file
  vars:
    master: "{{ master_ip }}"
  get_url:
    url: "http://{{ master }}:8080/jnlpJars/jenkins-cli.jar"
    dest: /home/ec2-user/jenkins-cli.jar
    force: yes
  register: download
  ignore_errors: yes
  until: download.status_code|default(200) == 200
  retries: 5
  delay: 5
  
- name: Allow execute perm to jenkins-cli.jar
  file:
    path: /home/ec2-user/jenkins-cli.jar
    owner: ec2-user
    group: ec2-user
    mode: '0777'
    
- name: Place Jenkins Auth file
  copy:
    src: files/jenkins_auth
    dest: /home/ec2-user/
    owner: ec2-user
    mode: '0600'

- name: Create Jenkins Credential
  vars:
    master: "{{ master_ip }}"
  shell: "cat /home/ec2-user/creds.xml | java -jar /home/ec2-user/jenkins-cli.jar -auth @/home/ec2-user/jenkins_auth -s http://{{master}}:8080 create-credentials-by-xml system::system::jenkins _"
