---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  roles:
    - role: system/install_jenkins_worker
  vars:
    master_ip: "0.0.0.0" # THIS NEEDS TO BE SPECIFIED ON RUN
  tags:
    - system_install
